### ISSUE TITLE
Emphasize Random Restarts in Evaluation

### ISSUE THREAD

**Issue by hendrycks** [evaluating-adversarial-robustness/adv-eval-paper#19]
In view of [this result](https://github.com/facebookresearch/ImageNet-Adversarial-Training/issues/1#issuecomment-470069171), perhaps this document should mention the importance of using many random restarts in Section "4.8 Verify Attack Convergence." It is mentioned in Section "4.9 Carefully Investigate Attack Hyperparmeters" but currently deemed "not necessary." Now restarts appear to be more important than previously thought.

**Comment by max-andr** [comment]
We also think that it should become a *necessary* standard. Based also on the results in [our NeurIPS workshop paper](https://arxiv.org/abs/1810.12042), it certainly makes sense to consider many random restarts. And not only in pathological cases like Clean Logit Pairing or Logit Squeezing (where the gradient is useful, but there are many local optima), but even for adversarially trained models.

But actually, the same observation was made even back in [Madry et al, 2018](https://arxiv.org/abs/1706.06083). For example, in their [mnist_challenge](https://github.com/MadryLab/mnist_challenge#white-box-leaderboard) they already note the influence of random restarts on adversarial accuracy for their model:
- 92.52% (1 random restart)
- 89.62% (50 random restarts)

Given the fact that it makes a difference even for an adversarially trained model, which is believed to not cause any gradient masking (e.g. see the discussion of [Uesato et al, 2018](https://arxiv.org/abs/1802.05666)), we believe it should become a standard for *all* models.

In this context, it's not surprising that the models from [Feature Denoising for Improving Adversarial Robustness](https://github.com/facebookresearch/ImageNet-Adversarial-Training/issues/1#issuecomment-470069171) also have a similar reduction in their adversarial accuracy:

| Model | Clean acc. | Adv. acc. reported with 1 random restart | Adv. acc. with 100 random restarts |
| -------- | -------- | -------- | -------- |
| ResNet152-baseline, 100% AT RND | 62.32% | 39.20% | **34.38%** | 
| ResNet152-denoise, 100% AT RND + feature denoising | 65.30% | 42.60% | **37.25%** | 

Especially, since there is a series of papers recently that try to marginally improve on top of adversarial training, obtaining as tight upper bounds on the true adversarial accuracy as possible is necessary to properly measure actual progress in defending against adversarial examples.
